http://repl.it/7ky
var instructions = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."; 

//start with first 2 terms and a variable to track the sum
var a = 1;
var b = 2;
var sum = 0;

//loop while a is less than 4 million
while( a < 4000000) {

//if a is even, add it to the sum
    if( a % 2 === 0){
        sum += a;
    }
    
//create a new variable "c" that holds the sum of a and b
//then finally update a and b as they keep adding
    var c = a + b;
    a = b;
    b = c;
}

//display the sum
console.log(sum);


/*
var a = 1;
var b = 2;
var sum = 0;

while(a < 4000000) {
    if(a%2===0) {
        sum += a;
    }
    var c = a + b;
    a = b;
    b = c;
}
*/
